# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 23, 15, 52, 2, 344525, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 23, 15, 52, 30, 436858, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
