# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20160823_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='distribution',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
