# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20160823_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('paused', 'paused'), ('offline', 'offline')], default='offline', max_length=50),
        ),
    ]
