# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distribution',
            table='"distributions"',
        ),
        migrations.AlterModelTable(
            name='locale',
            table='"locales"',
        ),
        migrations.AlterModelTable(
            name='market',
            table='"markets"',
        ),
        migrations.AlterModelTable(
            name='sourcetype',
            table='"source_types"',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='"surveys"',
        ),
    ]
