# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerhub', '0003_auto_20160810_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='begin_at',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_at',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
